services:
  - type: web
    name: malaria-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: serviceAccountKey.json
    runtime: python-3.10
    rootDir: backend
